### ISSUE TITLE
sodium error "Error: key must be a buffer of size 16U"

### ISSUE THREAD

**Issue by regular** [watson/npm-to-hypercore#4]
Hi, I just tried this out by running hypertail and got an Exception from sodium. Am I doing something wrong?

```
➜  ~ hypername init /tmp/npm-to-hypercore
6c2fe1705eab55a621835413e227adfe0ea2b004039eb041842af6279242e60d
➜  ~ hypertail /tmp/npm-to-hypercore f5d045813912dadbff4bdc8a43bb78da6685f965f1a88e430db49c793a5a1a01
/Users/regular/.nvm/versions/node/v6.3.1/lib/node_modules/hyperpipe/node_modules/hypercore/lib/hash.js:63
  sodium.crypto_generichash(digest, HYPERCORE, tree)
         ^

Error: key must be a buffer of size 16U
    at Error (native)
    at Object.exports.discoveryKey (/Users/regular/.nvm/versions/node/v6.3.1/lib/node_modules/hyperpipe/node_modules/hypercore/lib/hash.js:63:10)
    at new Feed (/Users/regular/.nvm/versions/node/v6.3.1/lib/node_modules/hyperpipe/node_modules/hypercore/index.js:53:40)
    at Feed (/Users/regular/.nvm/versions/node/v6.3.1/lib/node_modules/hyperpipe/node_modules/hypercore/index.js:26:39)
    at Object.<anonymous> (/Users/regular/.nvm/versions/node/v6.3.1/lib/node_modules/hyperpipe/index.js:30:12)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

**Comment by mafintosh** [comment]
I think hypername is running an very old version of hypercore, which would cause this. Will take a look
